In [1]:
import pandas as pd

In [7]:
df=pd.read_csv("data/sleep_dataset.csv")

In [9]:
df.shape

(374, 13)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    str
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    str
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    str
 9   Blood Pressure           374 non-null    str
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           155 non-null    str
dtypes: float64(1), int64(7), str(5)
memory usage: 38.1 KB

In [18]:
columns_to_be_renamed=df.columns.to_list()
column_name_mapper={}

for column in columns_to_be_renamed:
    column_name_mapper[column]=column.lower().replace(" ","_")

df=df.rename(columns=column_name_mapper)

df

,person_id,gender,age,occupation,sleep_duration,quality_of_sleep,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,No Sleep Order Recorded
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,No Sleep Order Recorded
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,No Sleep Order Recorded
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [23]:
df['sleep_disorder']=df['sleep_disorder'].fillna("No Sleep Order Recorded")

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                374 non-null    int64
 1   gender                   374 non-null    str
 2   age                      374 non-null    int64
 3   occupation               374 non-null    str
 4   sleep_duration           374 non-null    float64
 5   quality_of_sleep         374 non-null    int64
 6   physical_activity_level  374 non-null    int64
 7   stress_level             374 non-null    int64
 8   bmi_category             374 non-null    str
 9   blood_pressure           374 non-null    str
 10  heart_rate               374 non-null    int64
 11  daily_steps              374 non-null    int64
 12  sleep_disorder           374 non-null    str
dtypes: float64(1), int64(7), str(5)
memory usage: 38.1 KB

In [ ]:
#age_group || 0-12-->Kid 13-19-->Teen 20-27 -->Young Adult 28-50 --> Adult 50+-->Elder

In [ ]:
df.loc[df['age']<=12,'age_group']='Kid'
df.loc[(df['age']<=19) & (df['age']>12) ,'age_group']='Teen'
df.loc[(df['age']<=27) & (df['age']>19),'age_group']='Young Adult'
df.loc[(df['age']<=50) & (df['age']>27),'age_group']='Adult'
df.loc[df['age']>50,'age_group']='Elder'

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                374 non-null    int64
 1   gender                   374 non-null    str
 2   age                      374 non-null    int64
 3   occupation               374 non-null    str
 4   sleep_duration           374 non-null    float64
 5   quality_of_sleep         374 non-null    int64
 6   physical_activity_level  374 non-null    int64
 7   stress_level             374 non-null    int64
 8   bmi_category             374 non-null    str
 9   blood_pressure           374 non-null    str
 10  heart_rate               374 non-null    int64
 11  daily_steps              374 non-null    int64
 12  sleep_disorder           374 non-null    str
 13  age_group                374 non-null    str
dtypes: float64(1), int64(7), str(6)
memory usage: 41.0 KB

In [34]:
df.loc[df['bmi_category'].isin(['Normal Weight']),'bmi_category']='Normal'

In [39]:
#gender, occupation, bmi_category, sleep_disorder, age_group (category)
df[['gender','occupation','bmi_category','sleep_disorder','age_group']]=df[['gender','occupation','bmi_category','sleep_disorder','age_group']].astype("category")

df.dtypes

person_id                     int64
gender                     category
age                           int64
occupation                 category
sleep_duration              float64
quality_of_sleep              int64
physical_activity_level       int64
stress_level                  int64
bmi_category               category
blood_pressure                  str
heart_rate                    int64
daily_steps                   int64
sleep_disorder             category
age_group                  category
dtype: object

In [ ]:
# 130/85 --> Systolic=130 && Diastolic=85

# Optimal Blood Pressure --120/80 but 110-120(Normal) || 70-80(Normal)

blood_pressure
130/85    99
125/80    65
140/95    65
120/80    45
115/75    32
135/90    27
140/90     4
125/82     4
132/87     3
128/85     3
126/83     2
130/86     2
117/76     2
131/86     2
128/84     2
135/88     2
129/84     2
115/78     2
119/77     2
142/92     2
139/91     2
118/75     2
118/76     1
121/79     1
122/80     1
Name: count, dtype: int64

In [48]:
def get_systolic(value): #value = 130/85
    split_value=value.split("/") # -->[130,85]
    return split_value[0]

def get_disatolic(value):
    split_value=value.split("/")
    return split_value[1]

df['systolic']=df['blood_pressure'].apply(get_systolic)
df['diastolic']=df['blood_pressure'].apply(get_disatolic)

df[['systolic','diastolic']]=df[['systolic','diastolic']].astype("int")

df.dtypes

person_id                     int64
gender                     category
age                           int64
occupation                 category
sleep_duration              float64
quality_of_sleep              int64
physical_activity_level       int64
stress_level                  int64
bmi_category               category
blood_pressure                  str
heart_rate                    int64
daily_steps                   int64
sleep_disorder             category
age_group                  category
systolic                      int64
diastolic                     int64
systolic_indicator              str
dtype: object

In [49]:
# 110-120(Normal) || 70-80(Normal)
df.loc[df['systolic'] > 120 ,'systolic_indicator']='High'
df.loc[df['systolic']<110,'systolic_indicator']='Low'

df.loc[(df['systolic']<=120) & (df['systolic']>=110),'systolic_indicator']='Normal'

# 110-120(Normal) || 70-80(Normal)
df.loc[df['diastolic'] > 80 ,'diastolic_indicator']='High'
df.loc[df['diastolic']<70,'diastolic_indicator']='Low'

df.loc[(df['diastolic']<=70) & (df['diastolic']>=80),'diastolic_indicator']='Normal'


df

,person_id,gender,age,occupation,sleep_duration,quality_of_sleep,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder,age_group,systolic,diastolic,systolic_indicator,diastolic_indicator
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,No Sleep Order Recorded,Young Adult,126,83,High,High
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,No Sleep Order Recorded,Adult,125,80,High,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,No Sleep Order Recorded,Adult,125,80,High,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,Adult,140,90,High,High
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,Adult,140,90,High,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,Elder,140,95,High,High
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,Elder,140,95,High,High
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,Elder,140,95,High,High
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,Elder,140,95,High,High
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,Elder,140,95,High,High

In [51]:
#systolic !=Normal then final_indicator=systolic_indicator

#systolic ==Normal then final_indicator=diastolic_indicator

df.loc[df['systolic_indicator']!='Normal','final_indicator']=df['systolic_indicator']
df.loc[df['systolic_indicator']=='Normal','final_indicator']=df['diastolic_indicator']


df['final_indicator'].value_counts()

final_indicator
High    288
Name: count, dtype: int64